import isArray from './isArray';
import isBoolean from './isBoolean';
import isDate from './isDate';
import isEmpty from './isEmpty';
import isError from './isError';
import isFunction from './isFunction';
import isMap from './isMap';
import isNaN from './isNaN';
import isNil from './isNil';
import isNull from './isNull';
import isNumber from './isNumber';
import isObject from './isObject';
import isRegExp from './isRegExp';
import isSet from './isSet';
import isString from './isString';
import isSymbol from './isSymbol';
import isUndefined from './isUndefined';
declare const _default: {
    isArray: typeof isArray;
    isBoolean: typeof isBoolean;
    isDate: typeof isDate;
    isEmpty: typeof isEmpty;
    isError: typeof isError;
    isFunction: typeof isFunction;
    isMap: typeof isMap;
    isNaN: typeof isNaN;
    isNil: typeof isNil;
    isNull: typeof isNull;
    isNumber: typeof isNumber;
    isObject: typeof isObject;
    isRegExp: typeof isRegExp;
    isSet: typeof isSet;
    isString: typeof isString;
    isSymbol: typeof isSymbol;
    isUndefined: typeof isUndefined;
};
export default _default;
